### ISSUE TITLE
[1.0] Road to "1.0"

### ISSUE THREAD

**Issue by siejkowski** [Polidea/SiriusObfuscator#3]
This issue describes the roadmap to the first version that we believe is feature-complete enough to be called "1.0".

## Vision

The version 1.0 of Sirius obfuscator is the version that contains at least initial implementation of all the features that we believe that are crucial for using the tool in the majority of real-world apps.

## Scope

The roadmap is split into 9 steps, each one of them referenced by the increment on the minor version indicator:

* [ ] [0.2: Open sourcing the tool](https://github.com/Polidea/SiriusObfuscator/projects/1#card-11533038)
* [ ] [0.3: Support multiple Swift version](https://github.com/Polidea/SiriusObfuscator/projects/1#card-11533050)
* [ ] [0.4: Ability to rename multiple targets](https://github.com/Polidea/SiriusObfuscator/projects/1#card-11533054)
* [ ] [0.5: Initial support for the mixed Swift / Objective-C projects](https://github.com/Polidea/SiriusObfuscator/projects/1#card-11533083)
* [ ] [0.6: De-obfuscating the crash reports](https://github.com/Polidea/SiriusObfuscator/projects/1#card-11533068)
* [ ] [0.7: Missing Swift constructs](https://github.com/Polidea/SiriusObfuscator/projects/1#card-11533121)
* [ ] [0.8: Optimizations and performance improvements](https://github.com/Polidea/SiriusObfuscator/projects/1#card-11533128)
* [ ] [0.9: Improving user experience](https://github.com/Polidea/SiriusObfuscator/projects/1#card-11533134)
* [ ] [1.0: Polishing & bugfixing](https://github.com/Polidea/SiriusObfuscator/projects/1#card-11533138)

The high-level vision and the actual scope of each one of these versions is described in the linked issues.
